<style>

</style>

<div style="width: 900px; margin: 0 auto">
<h3 style="text-align: center">Список сообщений:</h3>
<?php
/** @var $message \App\Model\Message */
/** @var $user \App\Model\User */
$user = $this->user;
?>
<?php if($messages = $this->messages): ?>
    <div style="display: flex; flex-direction: column; gap: 20px">
    <?php foreach ($messages as $message): ?>
        <div style="width: 100%; border: 2px solid forestgreen; border-radius: 10px; padding: 5px">
            <?php if($user->isAdmin()): ?>
            <div class="admin">
                <a href="/admin/deleteMessage/?id=<?=$message->getId();?>">Удалить сообщение</a>
            </div>
            <?php endif; ?>
            <span style="color: darkgray"><?=$message->getCreatedAt();?> </span>
            <?php if($author = $message->getUser()):?>
                <span style="color: cornflowerblue"><?=htmlspecialchars($author->getName());?></span>
            <?php else: ?>
                <span style="color: red; text-decoration: line-through;">Пользователь удален</span>
            <?php endif; ?>
            <div style="border-top: 1px solid forestgreen; padding-top: 10px"><?=htmlspecialchars(nl2br($message->getText()));?></div>
            <?php if($message->getImage()):?>
                <div><img src="/images/<?=$message->getImage();?>" style="width: 150px;"></div>
            <?php endif;?>
        </div>
    <?php endforeach; ?>
    </div>
<?php else: ?>
    Нет сообщений... <br><br><br>
<?php endif; ?>

<form enctype="multipart/form-data" action="/blog/addMessage" method="post" style="width: 500px; margin: 0 auto">
    <h4>Добавить сообщение:</h4>
    <textarea style="width: 100%; height: 150px; padding: 15px; border-radius: 10px; border-color: tomato" type="text" value="" name="text"></textarea><br><br>
    Добавьте картинку: <input type="file" name="image"><br>
    <div style="text-align: center; margin-top: 30px">
        <input type="submit" value="Отправить" style="cursor: pointer; width: 200px; height: 30px;">
    </div>
</form>
</div>
